package com.ghalbitnet.meshx2.diagnostics.evidence

object RuntimeEvidenceTags {
    const val VIRTUAL_CALL_TRIGGER_RECEIVED = "VIRTUAL_CALL_TRIGGER_RECEIVED"
    const val VIRTUAL_CALL_TOOL_START = "VIRTUAL_CALL_TOOL_START"
    const val INCOMING_CALL_SCREEN_OPENED = "INCOMING_CALL_SCREEN_OPENED"
    const val RINGING_STARTED = "RINGING_STARTED"
    const val ACCEPT_PRESSED = "ACCEPT_PRESSED"
    const val CALL_ACCEPTED = "CALL_ACCEPTED"
    const val CALL_CONNECTED = "CALL_CONNECTED"
    const val AUDIO_CAPTURE_STARTED = "AUDIO_CAPTURE_STARTED"
    const val AUDIO_SPEECH_DETECTED = "AUDIO_SPEECH_DETECTED"
    const val RINGTONE_STOPPED = "RINGTONE_STOPPED"
    const val CALL_ENDED = "CALL_ENDED"
    const val RECOVERY_ACTION_APPLIED = "RECOVERY_ACTION_APPLIED"
    const val FAIL_STAGE = "FAIL_STAGE"

    const val SERVER_BASE_URL_CONFIGURED = "SERVER_BASE_URL_CONFIGURED"
    const val SERVER_HEALTH_OK = "SERVER_HEALTH_OK"
    const val SERVER_HEALTH_FAIL = "SERVER_HEALTH_FAIL"
    const val SERVER_REGISTER_OK = "SERVER_REGISTER_OK"
    const val SERVER_HEARTBEAT_OK = "SERVER_HEARTBEAT_OK"
    const val SERVER_RELAY_OK = "SERVER_RELAY_OK"
    const val SERVER_SESSION_OK = "SERVER_SESSION_OK"
    const val SERVER_NOT_CONFIGURED = "SERVER_NOT_CONFIGURED"

    const val MESSAGE_CREATED = "MESSAGE_CREATED"
    const val MESSAGE_SENT_TO_SERVER = "MESSAGE_SENT_TO_SERVER"
    const val MESSAGE_PENDING = "MESSAGE_PENDING"
    const val MESSAGE_DELIVERED = "MESSAGE_DELIVERED"
    const val MESSAGE_READ = "MESSAGE_READ"
    const val MEDIA_PENDING = "MEDIA_PENDING"
    const val FAILED_BEFORE_TTL_BLOCKED = "FAILED_BEFORE_TTL_BLOCKED"
}

