package com.ghalbitnet.meshx2.reliability

enum class OperationalApprovalStage {
    DIAGNOSTICS_APPROVED,
    TELEMETRY_APPROVED,
    BLOCKER_REVIEW_APPROVED,
    ESCALATION_REVIEW_APPROVED,
    GOVERNANCE_APPROVED,
    ROLLBACK_READINESS_APPROVED,
    ACTIVATION_ELIGIBILITY_APPROVED
}
