package com.ghalbitnet.meshx2.vpn

object MeshForwardProtocol {
    const val TYPE_VPN_FORWARD_PACKET = "VPN_FORWARD_PACKET"
    const val TYPE_VPN_FORWARD_RESPONSE = "VPN_FORWARD_RESPONSE"
    const val TYPE_VPN_RETURN_PACKET = "VPN_RETURN_PACKET"

    const val STATUS_OK = "OK"
    const val STATUS_EGRESS_FAILED = "EGRESS_FAILED"
    const val STATUS_UNSUPPORTED_PROTOCOL = "UNSUPPORTED_PROTOCOL"
    const val STATUS_SESSION_EXPIRED = "SESSION_EXPIRED"
    const val STATUS_DUPLICATE_PACKET = "DUPLICATE_PACKET"
    const val STATUS_INVALID_SOURCE = "INVALID_SOURCE"
    const val STATUS_POLICY_BLOCKED = "POLICY_BLOCKED"
    const val STATUS_TCP_CONNECT_FAILED = "TCP_CONNECT_FAILED"
    const val STATUS_TCP_WRITE_FAILED = "TCP_WRITE_FAILED"
    const val STATUS_TCP_RAW_PACKET_NEEDS_TRANSLATION = "TCP_RAW_PACKET_NEEDS_TRANSLATION"
}
