package com.ghalbitnet.meshx2.call

enum class CallState {
    IDLE,
    OUTGOING,
    RINGING,
    INCOMING,
    ACCEPT_CLICKED,
    SIGNALING_ACCEPT,
    WAITING_FOR_ROUTE,
    ROUTE_READY,
    WAITING_FOR_AUDIO_PATH,
    VOICE_HANDSHAKING,
    VOICE_TRANSPORT_READY,
    VOICE_STREAM_ACTIVE,
    PTT_FALLBACK,
    RELAY_NOT_CONFIGURED,
    RELAY_UNREACHABLE,
    MESH_STALE,
    CALL_CONNECTED_SIGNAL_ONLY,
    CALL_FAILED,
    CALL_ENDED,
    MISSED,
    REJECTED,
    CONNECTED,
    ENDED,
    FAILED
}
