package com.ghalbitnet.meshx2.online

enum class DeliveryStatus {
    LOCAL_SENT,
    INTERNET_SENT,
    ACCEPTED_BY_RELAY,
    QUEUED_REMOTE,
    MEDIA_UPLOADING,
    MEDIA_RESUMING,
    MEDIA_QUEUED_REMOTE,
    MEDIA_DELIVERED_REMOTE,
    MEDIA_READ_REMOTE,
    MEDIA_EXPIRED,
    DELIVERED_REMOTE,
    READ_REMOTE,
    EXPIRED_REMOTE,
    INTERNET_RELAY_NOT_CONFIGURED,
    PENDING_SYNC,
    FAILED
}
